### ISSUE TITLE
No need for Calendar µService, Proposition

### ISSUE THREAD

**Issue by Vaiktorg** [revaturelabs1801/hydra-calendar-service#6]
@msdewitt  The creation of a Calendar µService is not needed due to the fact that it only makes requests from TopicService and one Post method to the same TopicService. Considering merging it with Topic since it depends on it 100000%.

**Comment by msdewitt** [comment]
Alright, lets just add the calendar routes from the Calendar Controller from the original monolith to the Topic microservice.

**Comment by Vaiktorg** [comment]
µµµµµµµµµµµµµµµ Roger!
